# This workflow is necessary to support publishing to GitHub pages after renaming master to mainline since GitHub pages currently only support setting source from master branch

name: Push mainline changes into gh-pages branch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [mainline]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_master_branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build Documents
        - uses: actions/setup-node@v1
          with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'
        - run: npm install
        - run: npm run docs
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Publish documents" -a
      - name: Push changes
        uses: ad-m/github-push-action@gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs 